AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation demo template

Parameters:
  Environment:
    Description: Environment specific name
    Type: String

Resources:
  sqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub youtube-demo-cloudformation-${Environment}

  lambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "youtube-demo-lambda-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

        - PolicyName: allowSqs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !GetAtt MyQueue.Arn

  LambdaFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt sqsQueue.Arn
      FunctionName: !GetAtt lambdaFunction.Arn

  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub youtube-demo-cloudformation-${Environment}
      Handler: cloudformation-demo::cloudformation_demo.Function::FunctionHandler
      MemorySize: 128
      Role: !GetAtt lambdaExecutionRole.Arn
      Runtime: dotnet6
      Timeout: 60
      Environment:
        Variables:
          key1: value1 # A map of key-value pairs that the Lambda function can access
      Code:
        S3Bucket: youtube-packages-dev
        S3Key: lambda.zip
