AWSTemplateFormatVersion: 2010-09-09
Description: ---
Metadata:

Parameters:
  Environment:
    Description: Environment specific name
    Type: String

Resources:
  sqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub youtube-demo-cloudformation-${Environment}

  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub youtube-demo-cloudformation-${Environment}
      Handler: cloudformation-demo::cloudformation_demo.Function::FunctionHandler
      MemorySize: 128
      Role: role-arn
      Runtime: dotnetcore6.0
      Timeout: 60
      Environment:
        Variables:
          key1: value1 # A map of key-value pairs that the Lambda function can access
      Code:
        S3Bucket: youtube-packages-dev
        S3Key: lambda.zip
