name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Publish
      run: dotnet publish --no-self-contained --runtime linux-x64 --configuration Release --output /artifact/publish
      
    - name: action-zip
      # You may pin to the exact commit or the version.
      # uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
      uses: montudor/action-zip@v1.0.0
      with:
        # See montudor/action-zip README.md for more info
        args: zip -qq -r artifact/lambda.zip /artifact/publish
      
